apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-storage-class
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-persistent-volume-claim
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "mongo-storage-class"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:bionic
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-srv
  labels:
    app: mongo
spec:
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
